spring.application.name=PulseMQ

server.port=8080

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/pulsemq}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging Configuration
logging.level.root=INFO
logging.level.org.pulsemq.pulsemq=DEBUG
logging.level.org.springframework.web=WARN
logging.level.org.springframework.data=WARN
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.file.name=logs/pulsemq.log
logging.file.max-size=10MB
logging.file.max-history=10

